GS-8378 Upgrade to Maven 3.0
svn path=/trunk/openspaces/; revision=77829


Former-commit-id: 00ae8fd93fbc39bbdb0d7f1f601be17d5fd5f6a9

diff --git a/tools/maven/apache-maven-3.0/bin/mvnyjp b/tools/maven/apache-maven-3.0/bin/mvnyjp
--- a/tools/maven/apache-maven-3.0/bin/mvnyjp
+++ b/tools/maven/apache-maven-3.0/bin/mvnyjp
@@ -33,10 +33,6 @@
 #       set MAVEN_OPTS=-Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=8000
 # ----------------------------------------------------------------------------
 
-INT_MAVEN_OPTS="$MAVEN_OPTS -Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=8000"
-
-echo Preparing to Execute Maven in Debug Mode
-
 QUOTED_ARGS=""
 while [ "$1" != "" ] ; do
 
@@ -69,6 +65,10 @@ case "`uname`" in
            if [ -z "$JAVA_HOME" ] ; then
              JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Versions/${JAVA_VERSION}/Home
            fi
+           if [ -z "$YJP_HOME" ]; then
+             YJP_HOME=/Applications/YourKit.app
+           fi
+           YJPLIB=$YJP_HOME/bin/mac/libyjpagent.jnilib
            ;;
 esac
 
@@ -132,7 +132,7 @@ if [ -z "$JAVACMD" ] ; then
       JAVACMD="$JAVA_HOME/bin/java"
     fi
   else
-    JAVACMD=java
+    JAVACMD="`which java`"
   fi
 fi
 
@@ -146,7 +146,7 @@ if [ -z "$JAVA_HOME" ] ; then
   echo "Warning: JAVA_HOME environment variable is not set."
 fi
 
-CLASSWORLDS_LAUNCHER=org.codehaus.classworlds.Launcher
+CLASSWORLDS_LAUNCHER=org.codehaus.plexus.classworlds.launcher.Launcher
 
 # For Cygwin, switch paths to Windows format before running java
 if $cygwin; then
@@ -158,9 +158,16 @@ if $cygwin; then
     HOME=`cygpath --path --windows "$HOME"`
 fi
 
+if [ ! -f "$YJPLIB" ]; then
+  echo "Unable to autodetect the YJP library location. Please set YJPLIB variable"
+  exit 1
+fi
+
+MAVEN_OPTS="-agentpath:$YJPLIB=onexit=snapshot,onexit=memory,tracing,onlylocal $MAVEN_OPTS"
+
 exec "$JAVACMD" \
-  $INT_MAVEN_OPTS \
-  -classpath "${M2_HOME}"/boot/classworlds-*.jar \
+  $MAVEN_OPTS \
+  -classpath "${M2_HOME}"/boot/plexus-classworlds-*.jar \
   "-Dclassworlds.conf=${M2_HOME}/bin/m2.conf" \
   "-Dmaven.home=${M2_HOME}"  \
   ${CLASSWORLDS_LAUNCHER} $QUOTED_ARGS
